spring.application.name=proyecto-integrador-backend
spring.datasource.url=jdbc:mysql://localhost:3306/proyecto_integrador_backend
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update